### ISSUE TITLE
Wrong veriable in switch statement

### ISSUE THREAD

**Issue by d21d3q** [Gurux/Gurux.DLMS.cpp#1]
Why in `switch` statement in [line 481](https://github.com/Gurux/Gurux.DLMS.cpp/blob/master/GuruxDLMSClientExample/src/communication.cpp#L481) of `communication.cpp` `ret` variable is checked? Shouldn't be checked `ch` as maximum supported speed? 

BTW; is it right place to report such issues?

**Comment by gurux01** [comment]
Hi,

You are right. Thanks from this.
Get latest source codes.

**Comment by d21d3q** [comment]
Similar in line 513 baudRate -> ch

schould I pull request with such things?

**Comment by gurux01** [comment]
Hi,

You can just send email to me. It's faster. We check this tomorrow.

BR,

Mikko

----- Alkuperäinen viesti -----
Lähettäjä: "Zdzisław Krajewski" <notifications@github.com>
Lähetetty: ‎13.‎4.‎2016 18:05
Vastaanottaja: "Gurux/Gurux.DLMS.cpp" <Gurux.DLMS.cpp@noreply.github.com>
Kopio: "gurux01" <mikko.kurunsaari@gurux.fi>
Aihe: Re: [Gurux/Gurux.DLMS.cpp] Wrong veriable in switch statement (#1)

Similar in line 513 baudRate -> ch

schould I pull request with such things?
