### ISSUE TITLE
Compilation Client Error

### ISSUE THREAD

**Issue by matallanas** [Gurux/Gurux.DLMS.cpp#13]
Hello, I have an issue during the compilation of the client example.
The communication.cpp throw an error when assigning the value of NOPARITY, ODDPARITY, EVENPARITY, etc. because they are not declare.
Do I have to install any special library or maybe link something from the development?
Thank you very much.

**Comment by gurux01** [comment]
Hi,
Your OS is Windows? What compiler you are using?

**Comment by matallanas** [comment]
My OS is Ubuntu 16.10 and my compiler version g++ (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
Thank you very much.

**Comment by matallanas** [comment]
Hi, did you find any solution to this problem? 
Thank you very much.

**Comment by gurux01** [comment]
Hi,

We have updated client example today. Get latest version.
