### ISSUE TITLE
cfsetospeed - wrong parameters

### ISSUE THREAD

**Issue by d21d3q** [Gurux/Gurux.DLMS.cpp#2]
`cfsetospeed` and `cfsetispeed` are taking parameter of type `speed_t` which can have values of `B0` `B50` ... `B300` ... `B9600`. those values seems to be some enum - `B9600` is returning value 13. this is why `cfsetospeed (&options, 9600)` doesn't change speed to 9600

edit: 
file `communication.cpp`

**Comment by gurux01** [comment]
Hi,

You are right. This is fixed. Get latest version.

**Comment by d21d3q** [comment]
how about storing it in another value? eg not touching it in this switch
case, leave baudrate variable in form 9600 (which might be usefull for
printing) and add some switch statement in linux area right before serial
config. it will be more clear solution (less preprocessor directives)

how far is developement of this lib? I am trying to read Landis Gyr through
optical interface and I am getting assertion error from 1215 line of
*GXHelpers.cpp* file.
GXDLMSDirector shows me after some longer reading Access Error: Device
reports Read-Write denied.
Now I am compiling DLMSLib Client example with hope, that it is fully
working.
Are there any tricks for optical interface? or manufacturer specific?



2016-04-14 9:00 GMT+02:00 gurux01 <notifications@github.com>:

**Comment by gurux01** [comment]
Hi,

This example read all objects from the meter and that is not normally do..
Your Access error is error that meter returns we can't do anything with it.
Basically it means that Access for that attribute index is denied.

We are reading lots of different meters with this lib. Most of them are TCP/IP. 
Issues what you have found are in example, not in the parser.

**Comment by d21d3q** [comment]
Thanks.

One more question: if it reads all objects - does it mean that it will read
also historical data?


2016-04-14 10:34 GMT+02:00 gurux01 <notifications@github.com>:

**Comment by gurux01** [comment]
Hi,

Yes, we are supporting profile generics (historical data).
Actaris SL7000 and ACE 6000 are using non standard way, so you must use own implemetation to visualize data, but we can read all data from those meters also.

If you are using othere meters you can read all data without problems.

**Comment by d21d3q** [comment]
did you think about using boost libraries for code portability? it would
allow for using only one set of commands for serial communications,
filesystem handling etc.
It also have some commandline argumet parsing module (eg for specifying
port name, tcp/serial communication)

2016-04-14 11:03 GMT+02:00 gurux01 <notifications@github.com>:

**Comment by d21d3q** [comment]
it would eliminate preprocessor directives and make more readable

2016-04-14 12:37 GMT+02:00 Zdzisław Krajewski <zdzichucb@gmail.com>:

**Comment by gurux01** [comment]
Hi,

You can use boost library if you like to. Client example is used to collect all data from the meter. Gurux DLMS component do not care what communcation channel you are using. It just generates bytes to send and parses them from byte stream.
