### ISSUE TITLE
compile warning

### ISSUE THREAD

**Issue by meberli** [Gurux/Gurux.DLMS.cpp#4]
src/GXDLMSConverter.cpp: In static member function 'static const char* CGXDLMSConverter::ToString(DLMS_SECURITY_POLICY)':
src/GXDLMSConverter.cpp:488:5: warning: case value '3' not in enumerated type 'DLMS_SECURITY_POLICY' [-Wswitch]
     case 3:
     ^

**Comment by gurux01** [comment]
Hi,

We accidently updated SecuritySetup version 1 enum value over version 0. This is fixed. Get new version from GitHub.
